package org.dosomething.android.activities;

import org.dosomething.android.R;
import org.dosomething.android.cache.DSPreferences;

import android.app.Dialog;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager.NameNotFoundException;
import android.os.Bundle;
import android.os.Handler;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.TextView;

import com.google.inject.Inject;
import com.xtify.sdk.api.NotificationsPreference;
import com.xtify.sdk.api.XtifySDK;

public class Welcome extends AbstractActivity {
	
	@Inject private LayoutInflater inflater;
	
	// Xtify app key generated by app manager - see console.xtify.com/manage-app-keys
	final String XTIFY_APP_KEY = "4449bd82-e180-4ed7-8dc5-ecd9ff1738d0";
	// Sender ID is the Google API project #
	final String SENDER_ID = "1066768272703";
	private Dialog splashDialog;
	private boolean skipWelcome = true;
	
	@Override
	protected String getPageName() {
		return "welcome";
	}
	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.welcome);
		
		MyModel model = (MyModel) getLastNonConfigurationInstance();
        if (model != null) {
	        if (model.isShowSplashScreen()) {
	            showSplashScreen();
	        }
	    } else {
	    	if (getIntent().hasCategory("android.intent.category.LAUNCHER")) {
	    		showSplashScreen();
	    	}
	    }
        
        DSPreferences prefs = new DSPreferences(this);
        // If initial app execution, stay on the Welcome activity
        if (prefs != null && !prefs.getHasRun()) {
        	// Set boolean to indicate that this app has now been run
        	prefs.setHasRun();
        	skipWelcome = false;
        }
        else {
        	// On subsequent app executions, just send user to Profile page
        	skipWelcome = true;
        }
        
        // Setting up Xtify notifications settings
        Context context = getApplicationContext();
        NotificationsPreference.setVibrateEnabled(context, true);
        long[] vibratePattern = {0, 100, 200, 300};
        NotificationsPreference.setVibrationPattern(context, vibratePattern);
        NotificationsPreference.setIcon(context, R.drawable.ic_launcher);
        NotificationsPreference.setLightsEnabled(context, true);
        int ledARGB = 0xb99aff;
        int ledOnMS = 300;
        int ledOffMS = 1000;
        NotificationsPreference.setLights(context, new int[] {ledARGB, ledOnMS, ledOffMS});
	}
	
	@Override
	public void onStart() {
		super.onStart();
		XtifySDK.start(getApplicationContext(), XTIFY_APP_KEY, SENDER_ID);
//		String xid = XtifySDK.getXidKey(getApplicationContext());
//		String appkey = XtifySDK.getAppKey(getApplicationContext());
//		String ver = XtifySDK.getSdkVerNumber();
//		boolean notifEnabled = XtifySDK.isNotificationEnabled(getApplicationContext());
//		Log.v("XTIFY", "xid="+xid+" / appkey="+appkey+" / ver="+ver+" / notifEnabled="+notifEnabled);
	}
	
	public void continueToCauses(View v) {
		startActivity(new Intent(this, CauseSelector.class).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));
		finish();
	}
	
	@Override
	public Object onRetainNonConfigurationInstance() {
	    MyModel model = new MyModel();
	    
	    if (splashDialog != null) {
	        model.setShowSplashScreen(true);
	        removeSplashScreen();
	    }
	    return model;
	}
	
	/**
	 * Removes the Dialog that displays the splash screen
	 */
	protected void removeSplashScreen() {
		if (skipWelcome) 
			startActivity(new Intent(this, Profile.class).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));
	    
	    if (splashDialog != null) {
	    	splashDialog.dismiss();
	    	splashDialog = null;
	    }
	    
	    if (skipWelcome)
	    	finish();
	}
	 
	/**
	 * Shows the splash screen over the full Activity
	 */
	protected void showSplashScreen() {
		// Set the versionName in the splash screen
		String version = "";
		try {
			PackageInfo pInfo = this.getPackageManager().getPackageInfo(this.getPackageName(), 0);
			version = pInfo.versionName;
		}
		catch (NameNotFoundException e) {
		}

		View v = inflater.inflate(R.layout.splash_screen, null);
		if (version.length() > 0) {
			TextView tv = (TextView)v.findViewById(R.id.versionName);
			tv.setText(getString(R.string.splash_version)+version);
		}
		splashDialog = new Dialog(this, R.style.SplashScreen);
		splashDialog.setContentView(v);
		splashDialog.setCancelable(false);
		splashDialog.show();
	 
	    // Set Runnable to remove splash screen just in case
	    final Handler handler = new Handler();
	    handler.postDelayed(new Runnable() {
	      @Override
	      public void run() {
	        removeSplashScreen();
	      }
	    }, 3000);
	}
	
	/**
	 * Simple class for storing important data across config changes
	 */
	private class MyModel {
	    private boolean showSplashScreen = false;

		public boolean isShowSplashScreen() {
			return showSplashScreen;
		}
		public void setShowSplashScreen(boolean showSplashScreen) {
			this.showSplashScreen = showSplashScreen;
		}
	}

}
